# SnooYTBust config
Subreddit = ""

[database]
username = ""
password = ""
database = ""
host = ""
table = ""

[reddit]
clientid = ""
clientsecret = ""
Username = ""
Password = ""
UserAgent = "SnooYTBust v0.3 by /u/Try_to_guess_my_psn"

[services]
YTAPIKey = ""

# This is optional and can be kept empty.
[slack]
botUserToken = ""
notificationChannel = ""