# SnooYTBust config
Subreddit = ""

# This is optional and can be kept empty.
[slack]
botUserToken = ""
notificationChannel = ""

[database]
username = ""
password = ""
database = ""
host = ""

[reddit]
clientid = ""
clientsecret = ""
Username = ""
Password = ""
UserAgent = "SnooYTBust v0.1 by /u/Try_to_guess_my_psn"
RedirectURL = ""

[services]
YTAPIKey = ""